# Generated by Django 3.1 on 2020-08-26 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='quality',
            new_name='quantity',
        ),
    ]
